name: books
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.4
  dartz: ^0.10.1
  equatable: ^2.0.5
  logger: ^1.3.0
  cached_network_image: ^3.2.3
  path_provider: ^2.0.14
  gap: ^2.0.1
  intl: ^0.17.0
  flutter_riverpod: ^2.3.2
  flutter_localizations:
    sdk: flutter
  diacritic: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  tapped_lints:
    git:
      url: https://github.com/tappeddev/tapped_lints.git
      ref: master
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.2.0
  mocktail: ^0.3.0
  faker: ^2.1.0
  alchemist: ^0.6.0
  meta: ^1.8.0
  patrol: ^1.0.8

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - database/continue_books.json
    - database/books.json

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700

patrol:
  app_name: books
  android:
    package_name: com.example.books
  ios:
    bundle_id: com.example.books